<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/6/19
 * Time: 17:14
 */
namespace app\trade\controller;

use app\common\model\UserOrder;

class Financial extends Base{

    public $userOrder;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->userOrder= new UserOrder();

    }
    public function index(){

        $result=$this->userOrder->alias('a')->join('article b','a.goods_id=b.id')->where('a.complete_status','确认收货')->field('a.*,b.materials,b.jmoney')->paginate(10);

        $sum=$this->userOrder->alias('a')->join('article b','a.goods_id=b.id')->where('a.complete_status','确认收货')->sum('b.jmoney');

        $this->assign('sum',$sum);
        $this->assign('result',$result);
        return $this->fetch('index');
    }
}