<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/6/12
 * Time: 16:52
 */
namespace app\trade\controller;

use app\common\model\UserPerson;

class Person extends Base
{
    public $userPerson;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->userPerson = new UserPerson();

    }
    public function index(){
        $result=$this->userPerson->where('user_id',$this->id)->paginate(15);
        $this->assign('result',$result);
        return $this->fetch('person-list');
    }
    public function updPerson(){
        $param=$this->request->param();

        if($this->request->isPost()){

            $this->userPerson->save($param,['id'=>$param['id']]);
            return $this->redirect('index');
        }
        $info=$this->userPerson->where('id',$param['id'])->find();
        $this->assign('result',$info);
        return $this->fetch('update-person');
    }
    public function detail($id){
        return $this->fetch('person-detail');
    }
}