<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/6/12
 * Time: 16:52
 */
namespace app\trade\controller;

use app\common\model\UserPerson;

class Person extends Base
{
    public $userPerson;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->userPerson = new UserPerson();

    }
    public function index(){
        $result=$this->userPerson->where('user_id',$this->id)->paginate(15);
        $this->assign('result',$result);
        return $this->fetch('person-list');
    }
    //修改私人定制信息
    public function updPerson(){
        $param=$this->request->param();

        if($this->request->isPost()){

            $this->userPerson->save($param,['id'=>$param['id']]);
            return $this->redirect('index');
        }
        $info=$this->userPerson->where('id',$param['id'])->find();
        $this->assign('result',$info);
        return $this->fetch('update-person');
    }
    //私人定制详情
    public function detail($id){
        return $this->fetch('person-detail');
    }

    //ajax上传头像,做上传预览
    public function upload(){
        //最大上传图片2M
        $config = [
            'size' => 2097152,
            'ext'  => 'jpg,gif,png,bmp'
        ];

        $file=$this->request->file('file');

        if($file){
            $info = $file->validate($config)->move(ROOT_PATH . 'public' . DS . 'uploads');
            if($info){
                // 成功上传后 获取上传信息
                $result['url']='/public/uploads/'.$info->getSaveName();
                $result['code']=200;
            }else{
                // 上传失败获取错误信息
                $result['msg']=$file->getError();
                $result['code']=100;

            }
        }
        return json($result);
    }
}