<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/6/20
 * Time: 12:09
 */
namespace app\trade\controller;

use app\common\model\TradeNotice;

class Setting extends Base{
    public $tradeNotice;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->tradeNotice=new TradeNotice();
    }

    public function index(){
        $result=$this->tradeNotice->paginate(10);
        $this->assign('result',$result);
        return $this->fetch('notice-list');
    }
    //添加系统通知
    public function addNotice(){
        if($this->request->isPost()){
            $param=$this->request->param();
            $this->tradeNotice->save($param);
            return $this->redirect('index');
        }
        return $this->fetch('add-notice');
    }
    //移除系统通知
    public function remove($id){
        $this->tradeNotice->destroy($id);
        return 'ok';
    }
}