<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/5/8
 * Time: 17:00
 */
namespace app\user\controller;

use app\common\model\TradeNotice;

class Index extends Base{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->tradeNotice=new TradeNotice();
    }
    public function index(){

        return $this->fetch('index');
    }
    public function notice(){
        $result=$this->tradeNotice->paginate(10);
        $this->assign('result',$result);
        return $this->fetch('notice-list');
    }
    public function logout(){
        session(null);
        return $this->redirect('index/index/index');
    }

}