<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/5/8
 * Time: 17:00
 */
namespace app\user\controller;

use app\common\model\Article;
use think\Request;
use app\common\model\User as UserModel;

class Order extends Base{
    public $article;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->article=new Article();
    }


    //订单
    public function index($id=''){

        return $this->fetch('order-list');
    }
    //收藏
    public function favorite(){

        return $this->fetch();
    }
    //优惠劵
    public function coupons(){

        return $this->fetch();
    }
}