<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/5/8
 * Time: 17:00
 */
namespace app\user\controller;

use app\common\model\Article;
use app\common\model\UserOrder;

class Order extends Base{
    public $article;
    public $userOrder;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->article=new Article();
        $this->userOrder=new UserOrder();

    }

    //全部订单
    public function index($id=''){
        $this->assign('title','全部订单');
        $result=$this->userOrder->alias('a')->join('article b','a.goods_id=b.id')->where('a.user_id',$this->id)->field('a.*,b.thumb,b.title,b.materials,b.jmoney')->order('add_time desc')->paginate(5);
        $this->assign('result',$result);
        return $this->fetch('order-list');
    }
    //已经完成订单
    public function complete($id=''){
        $this->assign('title','已经完成订单');
        $result=$this->userOrder->alias('a')->join('article b','a.goods_id=b.id')->where('a.user_id',$this->id)->where("complete_status",'确认收货')->field('a.*,b.thumb,b.title,b.materials,b.jmoney')->order('add_time desc')->paginate(5);
        $this->assign('result',$result);
        return $this->fetch('order-list');
    }
    //未完成订单
    public function unfinished($id=''){
        $this->assign('title','未完成订单');
        $result=$this->userOrder->alias('a')->join('article b','a.goods_id=b.id')->where('a.user_id',$this->id)->where("complete_status",'未完成')->field('a.*,b.thumb,b.title,b.materials,b.jmoney')->order('add_time desc')->paginate(5);
        $this->assign('result',$result);
        return $this->fetch('order-list');
    }


    //ajax买家修改订单完成后的状态，收货或者退货
    public function setCompleteStatus($id,$status){
        $this->userOrder->save(['complete_status'=>$status,'complete_time'=>date('Y-m-d H:i:s')],['user_id'=>$this->id,'goods_id'=>$id]);
        return 'ok';

    }

}