<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/5/8
 * Time: 17:00
 */
namespace app\user\controller;

use app\common\model\Article;
use app\common\model\UserOrder;
use think\Request;
use app\common\model\User as UserModel;

class Order extends Base{
    public $article;
    public $userOrder;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->article=new Article();
        $this->userOrder=new UserOrder();

    }


    //订单
    public function index($id=''){
        $result=$this->userOrder->alias('a')->join('article b','a.goods_id=b.id')->where('a.user_id',$this->id)->field('b.*,a.add_time,a.order_status')->order('add_time')->paginate(5);
        $this->assign('result',$result);
        return $this->fetch('order-list');
    }
    //收藏
    public function favorite(){

        return $this->fetch();
    }
    //优惠劵
    public function coupons(){

        return $this->fetch();
    }
}