<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/6/12
 * Time: 16:52
 */
namespace app\user\controller;

use app\common\model\UserPerson;

class Person extends Base
{
    public $userPerson;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->userPerson = new UserPerson();

    }
    public function index(){

        $result=$this->userPerson->where('user_id',$this->id)->paginate(15);
        $this->assign('result',$result);
        return $this->fetch('person-list');
    }
    //添加
    public function addPerson(){
        if($this->request->isPost()){
            $param=$this->request->param();
            $param['user_id']=$this->id;
            $this->userPerson->save($param);
            return $this->redirect('index');
        }
        return $this->fetch('add-person');
    }
    public function detail($id){
        $result=$this->userPerson->field('img_list')->find($id);
        $this->assign('result',$result);
        return $this->fetch('person-detail');
    }
}